env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript/base
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  'import/no-extraneous-dependencies':
    - error
    - devDependencies:
      - "**/*.test.ts"
      - "**/*.spec.ts"
      - "vitest.config.ts"
    
